"""CommandCode provider profile override.

Replaces the bundled ``plugins/model-providers/commandcode/`` when installed as
a user plugin at ``$HERMES_HOME/plugins/model-providers/commandcode/``
(last-writer-wins in ``register_provider``). Registers:

``commandcode``
    ``api_mode=chat_completions`` — OpenAI-compatible endpoint.

``commandcode-anthropic``
    ``api_mode=anthropic_messages`` — Anthropic Messages API-compatible.

Both use the same ``COMMANDCODE_API_KEY`` env var and
``https://api.commandcode.ai/provider/v1`` base URL. Per-model metadata (image
input, reasoning capability, selectable reasoning efforts, per-model output
caps) comes from the checked-in ``catalog.py`` snapshot (regenerated by
``scripts/sync_catalog.py``) with ``catalog_overrides.py`` merged on top; the
model ID LIST is always fetched live from ``/models``, never hardcoded, and
each profile narrows it to the ids its own wire serves (``_wire_models``:
Claude on the Anthropic Messages wire, everything else on chat completions).
Pricing is injected into Hermes' ``_OFFICIAL_DOCS_PRICING`` at import
(side-effect) so ``/model`` cost badges and ``estimate_usage_cost`` resolve.
"""

from __future__ import annotations

import json
import logging
import urllib.request
from typing import Any

from providers import register_provider
from providers.base import ProviderProfile, _profile_user_agent

from . import cache
from . import catalog as _catalog_module
from .catalog import (
    MODEL_INPUT_MODALITIES,
    efforts_for_model,
    max_output_tokens_for_model,
    supports_image_input,
)
from .catalog_overrides import apply_overrides as _apply_catalog_overrides
from .pricing import ensure_pricing, install_pricing

logger = logging.getLogger(__name__)

# Claude models are served ONLY by the Anthropic Messages wire: calling one on
# /chat/completions answers 400 ``unsupported_model`` ("must be called via
# /provider/v1/messages"). Each profile therefore publishes exactly the ids its
# own endpoint accepts (live-verified 2026-09-25).
_ANTHROPIC_ONLY_PREFIX = "claude-"

# The generated catalog is an upstream mirror; this project's own capability
# declarations live in catalog_overrides.py and are merged in here, so every
# consumer (this profile, cache enrichment, the quota plugin's lazy loader)
# sees the same tables.
_apply_catalog_overrides(_catalog_module)

# ── Shared constants ──────────────────────────────────────────────────────────
_COMMANDCODE_BASE = "https://api.commandcode.ai/provider/v1"
_COMMANDCODE_MODELS_URL = f"{_COMMANDCODE_BASE}/models"
# Both profiles authenticate with the same key; each carries its own base-URL
# override var so each renders its own card on the desktop Keys tab.
_COMMANDCODE_ENV = ("COMMANDCODE_API_KEY", "COMMANDCODE_BASE_URL")
_COMMANDCODE_ANTHROPIC_ENV = ("COMMANDCODE_API_KEY", "COMMANDCODE_ANTHROPIC_BASE_URL")


def _fetch_commandcode_model_records(
    timeout: float = 10.0,
    base_url: str | None = None,
) -> list[dict] | None:
    """Fetch the live /models payload as raw ``{id, name, context_length}`` records.

    Returns the record list or None on failure. No auth required — the public
    models endpoint is open. ``base_url`` overrides the endpoint only when the
    caller passed a URL that differs from the default (a user-configured
    proxy/custom deployment); equality means "not customised".
    **The model catalog is always from this live fetch — never hardcoded.**
    """
    caller_base = (base_url or "").strip()
    if caller_base and caller_base.rstrip("/") != _COMMANDCODE_BASE.rstrip("/"):
        models_url = caller_base.rstrip("/") + "/models"
    else:
        models_url = _COMMANDCODE_MODELS_URL
    try:
        req = urllib.request.Request(models_url)
        req.add_header("Accept", "application/json")
        req.add_header("User-Agent", _profile_user_agent())
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            data = json.loads(resp.read().decode())
        return [
            m for m in data.get("data", []) if isinstance(m, dict) and "id" in m
        ]
    except Exception as exc:
        logger.debug("fetch_models(commandcode): %s", exc)
        return None


def _fetch_commandcode_models(
    timeout: float = 10.0,
    base_url: str | None = None,
) -> list[str] | None:
    """Fetch the whole live model ID list and refresh the on-disk catalog cache.

    Contract unchanged: returns the live ID list or None on failure (Hermes
    then falls back to the profile's ``fallback_models``). Each profile narrows
    this list to the ids its own endpoint serves (``_wire_models``). On success
    the raw records are enriched with catalog metadata and persisted via
    ``cache.enrich_models``/``cache.write_cache`` so the slash commands and
    later sessions see the last live-observed catalog.
    """
    records = _fetch_commandcode_model_records(timeout=timeout, base_url=base_url)
    if records is None:
        return None
    enriched = cache.enrich_models(records)
    try:
        cache.write_cache(cache.cache_path(), enriched)
    except OSError as exc:
        # A cache-write failure must never fail a live fetch.
        logger.debug("cache write failed: %s", exc)
    return [m["id"] for m in enriched]


# ── Reasoning-effort mapping ──────────────────────────────────────────────────
# Hermes effort vocabulary vs Command Code's. Clamp a requested effort onto the
# model's declared selectable set; unknown models expose no effort knob.
_HERMES_EFFORT_ORDER = ("minimal", "low", "medium", "high", "xhigh", "max")


def _clamp_effort(effort: str, declared: tuple[str, ...]) -> str | None:
    """Clamp a requested effort to the nearest supported level, or None."""
    if not declared:
        return None
    if effort in declared:
        return effort
    # Prefer the nearest weaker declared level; never escalate except through
    # the floor below, which exists because the endpoint rejects a level the
    # model does not declare (e.g. ``minimal`` → 400 on a low/high/max model).
    ordered = _HERMES_EFFORT_ORDER
    request_idx = next((i for i, e in enumerate(ordered) if e == effort), None)
    if request_idx is None:
        return None
    for level in reversed(ordered[:request_idx]):
        if level in declared:
            return level
    # Request sits below every declared level: use the model's floor.
    try:
        return min(declared, key=lambda x: ordered.index(x))
    except ValueError:
        return None


class CommandCodeProfile(ProviderProfile):
    """CommandCode — OpenAI-compatible chat completions endpoint."""

    def _wire_models(self, model_ids: list[str]) -> list[str]:
        """Narrow *model_ids* to the ids THIS profile's endpoint accepts.

        The OpenAI wire rejects Claude ids (400 ``unsupported_model``), so they
        are dropped here and published by ``CommandCodeAnthropicProfile``
        instead — a picker entry that every request 400s on is worse than no
        entry at all.
        """
        return [mid for mid in model_ids if not mid.startswith(_ANTHROPIC_ONLY_PREFIX)]

    def fetch_models(
        self,
        *,
        api_key: str | None = None,
        base_url: str | None = None,
        timeout: float = 8.0,
    ) -> list[str] | None:
        """Fetch from the public CommandCode /models endpoint (live, no hardcode).

        Also re-injects pricing if the import-time install was deferred by the
        circular-import guard — this runs (via /model) before any cost badge.
        """
        ensure_pricing()
        all_models = _fetch_commandcode_models(timeout=timeout, base_url=base_url)
        return None if all_models is None else self._wire_models(all_models)

    def default_vision_model(self) -> str | None:
        """A vision-capable model on THIS endpoint, for Hermes' vision auto-detect.

        Prefers a purpose-built ``*-vision*`` model, then the profile's auxiliary
        model when it takes images; None otherwise (Hermes then falls through to
        its aggregator chain). Model ids are checked against ``_wire_models`` so
        an endpoint never gets a model it cannot serve.
        """
        for model_id in MODEL_INPUT_MODALITIES:
            if "vision" in model_id.lower() and self._wire_models([model_id]):
                return model_id
        aux = self.default_aux_model
        if aux and supports_image_input(aux) and self._wire_models([aux]):
            return aux
        return None

    def get_max_tokens(self, model: str | None) -> int | None:
        if model:
            return max_output_tokens_for_model(model)
        return self.default_max_tokens

    def supported_reasoning_efforts(self, model: str | None) -> tuple[str, ...] | None:
        if not model:
            return None
        ensure_pricing()
        efforts = efforts_for_model(model)
        if not efforts:
            # Reasoning-capable but no declared levels → no effort knob.
            return ()
        return tuple(efforts)

    def build_api_kwargs_extras(
        self,
        *,
        reasoning_config: dict | None = None,
        model: str | None = None,
        **context,
    ) -> tuple[dict[str, Any], dict[str, Any]]:
        extra_body: dict[str, Any] = {}
        top_level: dict[str, Any] = {}
        if not model:
            return extra_body, top_level
        efforts = self.supported_reasoning_efforts(model)
        if efforts is None:
            return extra_body, top_level
        if isinstance(reasoning_config, dict):
            enabled = reasoning_config.get("enabled") is not False
            if not enabled:
                return extra_body, top_level
            effort = (reasoning_config.get("effort") or "").strip().lower()
            if effort and effort != "none":
                clamped = _clamp_effort(effort, efforts)
                if clamped is not None:
                    top_level["reasoning_effort"] = clamped
        return extra_body, top_level


commandcode = CommandCodeProfile(
    name="commandcode",
    aliases=("commandcode-chat",),
    api_mode="chat_completions",
    env_vars=_COMMANDCODE_ENV,
    display_name="CommandCode",
    description="CommandCode — 20+ models via OpenAI-compatible API",
    signup_url="https://commandcode.ai/",
    base_url=_COMMANDCODE_BASE,
    models_url=_COMMANDCODE_MODELS_URL,
    supports_vision=True,
    fallback_models=(
        "deepseek/deepseek-v4-pro",
        "deepseek/deepseek-v4-flash",
        "Qwen/Qwen3.7-Max",
        "Qwen/Qwen3.6-Plus",
        "moonshotai/Kimi-K2.6",
        "zai-org/GLM-5.1",
        "MiniMaxAI/MiniMax-M2.7",
        "stepfun/Step-3.5-Flash",
        "xiaomi/mimo-v2.5-pro",
        "google/gemini-3.5-flash",
        "gpt-5.5",
    ),
    default_aux_model="deepseek/deepseek-v4-flash",
)


class CommandCodeAnthropicProfile(CommandCodeProfile):
    """CommandCode — Anthropic Messages API-compatible endpoint (Bearer auth).

    Publishes ``claude-*`` ids only: the Anthropic Messages wire serves nothing
    else (every other model answers 400 "not supported on this endpoint"), and
    the OpenAI wire refuses Claude ids in turn.
    """

    def _wire_models(self, model_ids: list[str]) -> list[str]:
        return [mid for mid in model_ids if mid.startswith(_ANTHROPIC_ONLY_PREFIX)]


commandcode_anthropic = CommandCodeAnthropicProfile(
    name="commandcode-anthropic",
    aliases=("commandcode-claude",),
    api_mode="anthropic_messages",
    env_vars=_COMMANDCODE_ANTHROPIC_ENV,
    display_name="CommandCode (Anthropic)",
    description="CommandCode — Claude models via Anthropic Messages API",
    signup_url="https://commandcode.ai/",
    base_url=_COMMANDCODE_BASE,
    models_url=_COMMANDCODE_MODELS_URL,
    fallback_models=(
        "claude-sonnet-4-6",
        "claude-opus-4-7",
        "claude-haiku-4-5-20251001",
    ),
    default_aux_model="claude-haiku-4-5-20251001",
)


# ── Registration + pricing injection ──────────────────────────────────────────
register_provider(commandcode)
register_provider(commandcode_anthropic)
# Inject Command Code pricing into Hermes' official-docs table so /model cost
# badges and estimate_usage_cost resolve without editing a bundled core file.
install_pricing()
